#!/bin/bash

echo "$0 : $@"

# reloading systemd services
systemctl daemon-reload

echo "========================================================="
echo "* Avahi-Backup Client"
echo "* Please configure /etc/avahi-backup.d"
echo "========================================================="

systemctl restart avahi-backup-client.service
systemctl status avahi-backup-client.service


exit 0