#!/bin/bash


echo "$0 : $@"

systemctl --no-pager stop avahi-backup-client.service
systemctl --no-pager disable avahi-backup-client.service
systemctl --no-pager status avahi-backup-client.service


exit 0